<?php
/**
 * DSMP Ecommerce Content
 * /wp-admin/admin.php?page=ds-woo-content
 */
// phpcs:ignoreFile
if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_60c3691aca40e',
			'title'                 => 'Ecommerce content',
			'fields'                => array(
				array(
					'key'               => 'field_60c0879b7a313',
					'label'             => 'Product',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'placement'         => 'left',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60c345ptb9271',
					'label'             => '',
					'name'              => 'product_template',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_60c345ptb9272',
							'label'             => 'Product Template',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_60c3pt20b9273',
							'label'             => 'Display product categories',
							'name'              => 'display_product_categories',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
					),
				),
				array(
					'key'               => 'field_60c345e4b9271',
					'label'             => '',
					'name'              => 'product_help_widget',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_60c345f9b9272',
							'label'             => 'Product Help',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_60c34620b9273',
							'label'             => 'Product Help',
							'name'              => 'product_help',
							'type'              => 'checkbox',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'enable' => 'enable',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'vertical',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_60c3477f8679a',
							'label'             => 'Button Title',
							'name'              => 'button_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => 'Request a quote',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c3477f8679b',
							'label'             => 'Button Text',
							'name'              => 'button_text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => 'Request a quote',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c3477f867ti',
							'label'             => 'Form Title',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c3477f867su',
							'label'             => 'Form Subtitle',
							'name'              => 'subtitle',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c3477f867ph',
							'label'             => 'Form Phone',
							'name'              => 'phone',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c3477f867te',
							'label'             => 'Form Text',
							'name'              => 'text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_625d4b0127072',
							'label'             => 'Gravity Form',
							'name'              => 'gravity_form',
							'type'              => 'forms',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34620b9273',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'id',
							'allow_null'        => 0,
							'multiple'          => 0,
						),
					),
				),
				array(
					'key'               => 'field_60c34a0689784',
					'label'             => '',
					'name'              => 'product_cta_banner',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_60c34a0689785',
							'label'             => 'CTA Banner',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_60c34a0689786',
							'label'             => 'CTA Banner',
							'name'              => 'cta_banner',
							'type'              => 'checkbox',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'choices'           => array(
								'enable' => 'enable',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'vertical',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_60c34a5c89789',
							'label'             => 'Title',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34a0689786',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_60c34a6f8978a',
							'label'             => 'Text',
							'name'              => 'text',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34a0689786',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => 4,
							'new_lines'         => 'wpautop',
						),
						array(
							'key'               => 'field_60c34a858978b',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34a0689786',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_60c34aa28978c',
							'label'             => 'Background image',
							'name'              => 'background_image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_60c34a0689786',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'url',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
				// Shipping info
				array(
					'key'               => 'field_60c34sp689784',
					'label'             => '',
					'name'              => 'shipping_bar',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_60c34sp689785',
							'label'             => 'Shipping Bar',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_625ec1dde0157',
							'label'             => 'Shipping bar',
							'name'              => 'shipping_bar',
							'type'              => 'checkbox',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'enable' => 'enable',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'vertical',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_70e800801e6bc',
							'label'             => 'Is sticky?',
							'name'              => 'shipping_is_sticky',
							'type'              => 'checkbox',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_625ec1dde0157',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '33',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'enable' => 'enable',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'vertical',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_70e800802e6bc',
							'label'             => 'Shipping position',
							'name'              => 'shipping_position',
							'type'              => 'button_group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_70e800801e6bc',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '33',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'choices'           => array(
								'left'  => 'left',
								'right' => 'right',
							),
							'allow_null'        => 0,
							'default_value'     => 'right',
							'layout'            => 'horizontal',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_70e800803e6bc',
							'label'             => 'Is expendable?',
							'name'              => 'shipping_expendable',
							'type'              => 'checkbox',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_70e800801e6bc',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '33',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'enable' => 'enable',
							),
							'allow_custom'      => 0,
							'default_value'     => array(),
							'layout'            => 'vertical',
							'toggle'            => 0,
							'return_format'     => 'value',
							'save_custom'       => 0,
						),
						array(
							'key'               => 'field_625ec215e0158',
							'label'             => 'Content',
							'name'              => 'content',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_625ec1dde0157',
										'operator' => '==',
										'value'    => 'enable',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'collapsed'         => '',
							'min'               => 1,
							'max'               => 0,
							'layout'            => 'block',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_625ec22be0159',
									'label'             => 'Icon',
									'name'              => 'icon',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '20',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'return_format'     => 'array',
									'preview_size'      => 'thumbnail',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'field_625ec236e015a',
									'label'             => 'Title',
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '30',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'ds_default_value'  => 0,
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_625ec243e015b',
									'label'             => 'Text',
									'name'              => 'text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '30',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'ds_default_value'  => 0,
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_625ec24ce015c',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '20',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'return_format'     => 'array',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_60c9bf2309b5a',
					'label'             => 'Shop',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'placement'         => 'left',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60c9bf2c09b5b',
					'label'             => 'Subheader image',
					'name'              => 'shop_background',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'return_format'     => 'url',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_60e824803e6bc',
					'label'             => 'Header',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60c7598340186',
					'label'             => 'Cart link',
					'name'              => 'cart_link',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'choices'           => array(
						'enable'  => 'enable',
						'disable' => 'disable',
					),
					'allow_null'        => 0,
					'default_value'     => 'enable',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_60b4bdecef2ff',
					'label'             => 'Cart icon link title',
					'name'              => 'cart_icon_link_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60c7598340186',
								'operator' => '==',
								'value'    => 'enable',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'Cart',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60c75a624018a',
					'label'             => 'My Account links',
					'name'              => 'my_account_link',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'choices'           => array(
						'enable'  => 'enable',
						'disable' => 'disable',
					),
					'allow_null'        => 0,
					'default_value'     => 'enable',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_60b4be05ef300',
					'label'             => 'Login icon link title',
					'name'              => 'login_icon_link_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60c75a624018a',
								'operator' => '==',
								'value'    => 'enable',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'Login',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60b4c079f4f08',
					'label'             => 'Logout icon link title',
					'name'              => 'logout_icon_link_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60c75a624018a',
								'operator' => '==',
								'value'    => 'enable',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'Logout',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60b4be2def301',
					'label'             => 'Register icon link title',
					'name'              => 'register_icon_link_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60c75a624018a',
								'operator' => '==',
								'value'    => 'enable',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'Register',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60b4bf76a2188',
					'label'             => 'Account icon link title',
					'name'              => 'account_icon_link_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60c75a624018a',
								'operator' => '==',
								'value'    => 'enable',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'My Account',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60c087e2e84b2',
					'label'             => 'Mini Cart',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'placement'         => 'left',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_62e1a45b05037',
					'label'             => '',
					'name'              => 'empty_cart_content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_62e1a49105038',
							'label'             => 'Empty cart content',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62e1a4c005039',
							'label'             => 'Title',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62e1a4ca0503a',
							'label'             => 'Subtitle',
							'name'              => 'subtitle',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62e1a129af831',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_62e1a4d70503c',
							'label'             => 'Image',
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '20',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'array',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
				array(
					'key'               => 'field_62e1a4ea0503d',
					'label'             => '',
					'name'              => 'cart_content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_62e1a4fb0503e',
							'label'             => 'Cart content',
							'name'              => '',
							'type'              => 'accordion',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'open'              => 0,
							'multi_expand'      => 0,
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_62e1a5150503f',
							'label'             => 'Free shipping',
							'name'              => 'free_shipping',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62e1a6e9af831',
							'label'             => 'Cart link',
							'name'              => 'cart_link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_62e1a57005041',
							'label'             => 'Cart link subtitle',
							'name'              => 'cart_link_subtitle',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '60',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62e1a58005042',
							'label'             => 'Additional products title',
							'name'              => 'additional_products_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_62e1a5a205043',
							'label'             => 'Additional products type',
							'name'              => 'additional_products_type',
							'type'              => 'button_group',
							'instructions'      => 'manual - choose products
										   cross sells - load automatically for products from cart',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'manual'      => 'manual',
								'cross_sells' => 'cross sells',
							),
							'allow_null'        => 0,
							'default_value'     => '',
							'layout'            => 'horizontal',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_63e5224e362bc',
							'label'             => 'Products',
							'name'              => 'products',
							'aria-label'        => '',
							'type'              => 'relationship',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_62e1a5a205043',
										'operator' => '==',
										'value'    => 'manual',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'ds_default_value'  => 0,
							'post_type'         => array(
								0 => 'product',
							),
							'taxonomy'          => '',
							'filters'           => array(
								0 => 'search',
							),
							'return_format'     => 'object',
							'min'               => '',
							'max'               => '',
							'elements'          => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'ds-woo-content',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
